server:
  port: 8083

spring:
  # elasticsearch配置
  elasticsearch:
    rest:
      # 节点地址
      # uris: 192.168.58.175:9200,192.168.58.175:9201,192.168.58.175:9202
      uris: 192.168.111.175:9200
  datasource:
    url: jdbc:mysql://liuyuncen.com:3388/cloud?characterEncoding=utf8&useSSL=false&serverTimezone=Asia/Shanghai&rewriteBatchedStatements=true
    username: cloud
    password: cloud
    driver-class-name: com.mysql.cj.jdbc.Driver
